services:
  db:
    image: mysql:5.7
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user_name
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306" 
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      TZ: Asia/Tokyo
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    tty: true
    stdin_open: true  
    depends_on:
      - db
      - chrome
    ports:
      - "3000:3000"
    volumes:
      - .:/to_do_application
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
  chrome:
    image: seleniarm/standalone-chromium:121.0
    ports:
      - 4444:4444    
volumes:
  db-data:
  bundle_data:
  node_modules: